"""
Plate-solving wrapper around ESA's tetra3 (lost-in-space star-pattern solver).

The solver turns a camera image into an absolute sky position (RA/Dec/roll) without any
prior pointing knowledge. We convert that to topocentric az/el at the frame's timestamp
and compare it to the mount's reported encoder position to recover the instantaneous
alignment -- and, in Phase 4, to sample a full pointing model.

tetra3 is imported lazily so the rest of the app runs even when it isn't installed.
"""

import math
import os
import threading
from dataclasses import dataclass, field

import numpy as np


# Name of the database used in the simulator demo (generated by tools/build_tetra3_db.py
# for ~4-12 deg FOV). Falls back to tetra3's bundled 'default_database' (10-30 deg).
DEFAULT_SIM_DB = "db_fov12_mag7"


def tetra3_available():
    """True if the tetra3 package can be imported."""
    try:
        import tetra3  # noqa: F401
        return True
    except Exception:
        return False


def camera_fov_deg(config_state, cam_name, width_px=None, height_px=None):
    """Horizontal field of view (deg) for a camera, from its optics + sensor width."""
    from transformations import compute_fov_for_camera
    pix = float(config_state.get_camera_pixel_size(cam_name))
    foc = float(config_state.get_camera_focal_length(cam_name))
    if width_px is None or height_px is None:
        sim = getattr(config_state, 'sim_config', {}) or {}
        width_px = width_px or int(sim.get('cam_width', 960))
        height_px = height_px or int(sim.get('cam_height', 720))
    fov = compute_fov_for_camera(pix, foc, 1.0, 1.0, width_px, height_px)
    return float(fov['fov_width_deg'])


@dataclass
class SolveResult:
    ra_deg: float
    dec_deg: float
    roll_deg: float
    fov_deg: float
    rmse: float
    n_matches: int
    prob: float
    matched_centroids: np.ndarray = field(default_factory=lambda: np.empty((0, 2)))

    @property
    def solved(self):
        return self.n_matches > 0


# Module-level cache of loaded Tetra3 instances keyed by database name (the .npz is big).
_SOLVER_CACHE = {}
_SOLVER_LOCK = threading.Lock()


def _tetra3_data_dir():
    import tetra3
    return os.path.join(os.path.dirname(tetra3.__file__), 'data')


def _resolve_db_name(config_state, cam_name, fov_deg):
    """Pick a database for this camera's FOV.

    Priority: an explicit per-camera config (camera_configs[cam]['tetra3_db']), then the
    FOV-matched generated sim DB (~4-14 deg), then tetra3's bundled default_database
    (10-30 deg). Narrow-FOV real cameras should set an explicit DB generated for their
    field via tools/build_tetra3_db.py.
    """
    cam_cfg = config_state.get_camera_config(cam_name) if config_state else {}
    explicit = (cam_cfg or {}).get('tetra3_db')
    if explicit:
        return explicit
    data_dir = _tetra3_data_dir()
    sim_db_exists = os.path.exists(os.path.join(data_dir, DEFAULT_SIM_DB + '.npz'))
    if 4.0 <= fov_deg <= 14.0 and sim_db_exists:
        return DEFAULT_SIM_DB
    if fov_deg >= 10.0:
        return 'default_database'
    # Out of range of any available DB; fall back to the sim DB if present and warn.
    if sim_db_exists:
        print(f"PlateSolver: no DB matches {fov_deg:.1f} deg FOV; using {DEFAULT_SIM_DB}. "
              f"Generate one with tools/build_tetra3_db.py and set camera_configs['{cam_name}']['tetra3_db'].")
        return DEFAULT_SIM_DB
    return 'default_database'


class PlateSolver:
    """Loads a tetra3 database (cached) and solves frames for a given camera."""

    def __init__(self, config_state, cam_name='camera1'):
        self.config_state = config_state
        self.cam_name = cam_name
        self.fov_deg = camera_fov_deg(config_state, cam_name)
        self.db_name = _resolve_db_name(config_state, cam_name, self.fov_deg)
        self._t3 = None

    def ensure_loaded(self):
        """Load (and cache) the tetra3 database. Raises if tetra3 is missing."""
        if self._t3 is not None:
            return self._t3
        import tetra3
        with _SOLVER_LOCK:
            t3 = _SOLVER_CACHE.get(self.db_name)
            if t3 is None:
                t3 = tetra3.Tetra3(load_database=self.db_name)
                _SOLVER_CACHE[self.db_name] = t3
            self._t3 = t3
        return self._t3

    def solve(self, image, fov_estimate=None):
        """Solve a 2-D grayscale image. Returns SolveResult|None.

        fov_estimate defaults to the camera's computed FOV, which dramatically speeds
        and stabilises the search.
        """
        if image is None:
            return None
        t3 = self.ensure_loaded()
        if fov_estimate is None:
            fov_estimate = self.fov_deg
        img = np.asarray(image)
        if img.ndim == 3:
            img = img[..., 0]
        if img.dtype != np.uint8:
            img = np.clip(img, 0, 255).astype(np.uint8)
        # tetra3 expects a PIL Image (it reads image.size), so wrap the array.
        from PIL import Image
        pil_img = Image.fromarray(img)
        try:
            # Lenient matching for narrow FOVs: check more candidate patterns, allow a
            # larger centroid match radius, and relax the false-match threshold from
            # tetra3's strict 1e-3 to 1e-2. At ~1 deg FOV only ~5-10 stars match, so the
            # strict gate rejects otherwise-valid solutions; 1e-2 still solves wide
            # frames (more matches -> far lower false-positive prob).
            res = t3.solve_from_image(pil_img, fov_estimate=fov_estimate,
                                      fov_max_error=fov_estimate * 0.6,
                                      pattern_checking_stars=12, match_radius=0.02,
                                      match_threshold=1e-2, return_matches=True)
        except Exception as e:
            print(f"PlateSolver.solve error: {e}")
            return None
        if res is None or res.get('RA') is None:
            return SolveResult(float('nan'), float('nan'), float('nan'),
                               float('nan'), float('nan'), 0, 1.0)
        centroids = res.get('matched_centroids')
        centroids = np.asarray(centroids) if centroids is not None else np.empty((0, 2))
        return SolveResult(
            ra_deg=float(res['RA']), dec_deg=float(res['Dec']),
            roll_deg=float(res.get('Roll') or 0.0), fov_deg=float(res.get('FOV') or fov_estimate),
            rmse=float(res.get('RMSE') or float('nan')),
            n_matches=int(res.get('Matches') or 0),
            prob=float(res.get('Prob') if res.get('Prob') is not None else 1.0),
            matched_centroids=centroids,
        )


# ---- coordinate helpers -----------------------------------------------------

def solved_azel(ra_deg, dec_deg, lat_deg, lon_deg, elev_m, ephemeris, ts, t):
    """Convert a solved (RA, Dec) [J2000 deg] to topocentric (az, el) [deg] at time t.

    Uses Skyfield's apparent() so precession/nutation/aberration are applied the same
    way the simulator renders catalogue stars -- keeping solve and truth in one frame.
    """
    from skyfield.api import Star, wgs84
    earth = ephemeris['earth']
    star = Star(ra_hours=ra_deg / 15.0, dec_degrees=dec_deg)
    observer = earth + wgs84.latlon(lat_deg, lon_deg, elevation_m=elev_m)
    alt, az, _ = observer.at(t).observe(star).apparent().altaz()
    return float(az.degrees), float(alt.degrees)


def instantaneous_alignment_azimuth(az_solved, mount_azm):
    """AltAz instantaneous alignment azimuth: cam_az = (AZM + align) % 360.

    Returns align in (-180, 180]. Elevation alignment is intentionally NOT derived here:
    the AltAz forward transform ignores it (see transformations.AzAlt2AzEl_AltAz), so
    elevation correction belongs to the Phase-4 pointing model's IE term.
    """
    return ((az_solved - mount_azm + 180.0) % 360.0) - 180.0
