"""Generate the skyfield/Python reference fixture for tests/passes.rs.

Run from the repo root with the `track` conda env:

    C:/Users/nikke/anaconda3/envs/track/python.exe rust/skytracker-astro/tests/gen_passes_ref.py

Writes rust/skytracker-astro/tests/fixtures/passes_ref.txt. The fixture
embeds the exact TLE lines, observer and start epoch it used, so it stays
valid after tle_cache.tle is refreshed.

Semantics mirror the pygame pass table (trajectory.py): visible means
el > mask (strict); TCA = maximum elevation (magnitude evaluated there via
trajectory._estimate_pass_magnitude, the real app code path); apogee /
perigee per satellite_data.create_satellite_labels_and_metadata. AOS/LOS are
the mask crossings, linearly interpolated on a 1 s grid (the app table only
ever saw 30 s samples and never printed AOS/LOS; the Rust port refines
crossings, so the reference does the same to make the comparison tight).
"""
import json
import math
import os
import sys

import numpy as np

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
os.chdir(REPO)
sys.path.insert(0, REPO)
os.environ.setdefault("SDL_VIDEODRIVER", "dummy")

from skyfield.api import EarthSatellite, load, wgs84  # noqa: E402

import trajectory  # noqa: E402  (headless-safe; does not start the app)

MIN_EL = 10.0
HORIZON_H = 24.0
STEP_S = 1.0
# ISS, HST, CALSPHERE 1 (polar), TDRS/GEO candidates handled below.
WANTED = ["25544", "20580", "00900", "28358", "36097"]


def read_tles(path):
    with open(path, "r", errors="replace") as f:
        lines = [l.rstrip("\r\n").rstrip() for l in f if l.strip()]
    out = {}
    i = 0
    while i + 2 < len(lines):
        if lines[i + 1].startswith("1 ") and lines[i + 2].startswith("2 "):
            l1, l2 = lines[i + 1], lines[i + 2]
            out[l1[2:7].strip()] = (lines[i].strip(), l1, l2)
            i += 3
        else:
            i += 1
    return out


def main():
    cfg = json.load(open("config.json"))
    lat, lon, alt = float(cfg["lat"]), float(cfg["lon"]), float(cfg["alt"])
    tles = read_tles("tle_cache.tle")
    ts = load.timescale()
    eph = load("de421.bsp")
    earth, sun = eph["earth"], eph["sun"]
    observer = wgs84.latlon(lat, lon, elevation_m=alt)

    sats = []
    for sn in WANTED:
        if sn in tles:
            name, l1, l2 = tles[sn]
            sats.append((sn, name, l1, l2, EarthSatellite(l1, l2, name, ts)))
    iss = [s for s in sats if s[0] == "25544"][0][4]
    # Start at the ISS TLE epoch (UTC) -> TT.
    t_start = ts.tt_jd(ts.utc(iss.epoch.utc_datetime()).tt)
    start_tt = float(t_start.tt)

    n = int(HORIZON_H * 3600.0 / STEP_S) + 1
    times = ts.tt_jd(start_tt + np.arange(n) * STEP_S / 86400.0)

    MU = 3.986004418e14
    R_EARTH = 6371.0

    lines_out = []
    lines_out.append("# generated by rust/skytracker-astro/tests/gen_passes_ref.py (skyfield %s)" % __import__("skyfield").__version__)
    lines_out.append("observer %.10f %.10f %.3f" % (lat, lon, alt))
    lines_out.append("start_tt %.12f" % start_tt)
    lines_out.append("horizon_h %.3f" % HORIZON_H)
    lines_out.append("min_el %.3f" % MIN_EL)
    for sn, name, l1, l2, sat in sats:
        lines_out.append("tle %s|%s|%s|%s" % (sn, name, l1, l2))

    for sn, name, l1, l2, sat in sats:
        topo = (sat - observer).at(times)
        el, az, dist = topo.altaz()
        el = np.asarray(el.degrees)
        az = np.asarray(az.degrees)
        dist = np.asarray(dist.km)
        tt = np.asarray(times.tt)
        above = el > MIN_EL

        nmm = sat.model.no_kozai / 60.0
        a_km = (MU / nmm ** 2) ** (1.0 / 3.0) / 1000.0
        e = sat.model.ecco
        apogee = a_km * (1 + e) - R_EARTH
        perigee = a_km * (1 - e) - R_EARTH

        i = 0
        while i < n:
            if not above[i]:
                i += 1
                continue
            j = i
            while j + 1 < n and above[j + 1]:
                j += 1
            # run is [i, j]
            if i == 0:
                aos = tt[0]
                aos_trunc = 1
            else:
                f = (MIN_EL - el[i - 1]) / (el[i] - el[i - 1])
                aos = tt[i - 1] + f * (tt[i] - tt[i - 1])
                aos_trunc = 0
            if j == n - 1:
                los = tt[n - 1]
                los_trunc = 1
            else:
                f = (MIN_EL - el[j]) / (el[j + 1] - el[j])
                los = tt[j] + f * (tt[j + 1] - tt[j])
                los_trunc = 0
            k = i + int(np.argmax(el[i:j + 1]))
            tca = tt[k]
            if i < k < j:
                y0, y1, y2 = el[k - 1], el[k], el[k + 1]
                den = y0 - 2 * y1 + y2
                if abs(den) > 1e-12:
                    off = 0.5 * (y0 - y2) / den
                    tca = tt[k] + max(-1.0, min(1.0, off)) * (STEP_S / 86400.0)
            t_tca = ts.tt_jd(tca)
            el_tca, az_tca, d_tca = (sat - observer).at(t_tca).altaz()
            r_sun = earth.at(t_tca).observe(sun).position.km
            mag = trajectory._estimate_pass_magnitude(sat, t_tca, observer, r_sun)
            mag_s = "ecl" if mag is None else "%.4f" % mag
            lines_out.append(
                "pass %s %.10f %.10f %.10f %.4f %.4f %.3f %s %.3f %.3f %d %d"
                % (sn, aos, tca, los, float(el_tca.degrees), float(az_tca.degrees),
                   float(d_tca.km), mag_s, apogee, perigee, aos_trunc, los_trunc)
            )
            i = j + 1

    out_dir = os.path.join(REPO, "rust", "skytracker-astro", "tests", "fixtures")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "passes_ref.txt")
    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(lines_out) + "\n")
    print("wrote", out_path, "(%d lines)" % len(lines_out))
    for l in lines_out:
        if l.startswith("pass"):
            print(l)


if __name__ == "__main__":
    main()
