"""Generate rust/skytracker-astro/src/generated_tables.rs from skyfield data.

Phase 1 of the Rust port. The IAU 2000A nutation series (1,365 terms), the
equation-of-the-equinoxes complementary terms, the frame-bias matrix, and a
sampled delta-T curve are copied VERBATIM from the installed skyfield's own
bundled arrays -- hand-typing thousands of coefficients would invite typos,
and using skyfield's exact tables makes the Rust output bit-comparable to
the golden vectors (tests/golden/) that were recorded with skyfield.

Rerun only if skyfield is upgraded AND the goldens are re-recorded:

    C:\\Users\\nikke\\anaconda3\\envs\\track\\python.exe tools/gen_astro_tables.py
"""

from __future__ import annotations

import os

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "rust", "skytracker-astro", "src", "generated_tables.rs")


def fmt_f64(x: float) -> str:
    """repr() round-trips f64 exactly; ensure Rust float literal syntax."""
    s = repr(float(x))
    if "e" in s or "E" in s:
        mant, _, exp = s.partition("e")
        if "." not in mant and "inf" not in mant and "nan" not in mant:
            mant += ".0"
        return mant + "e" + exp
    if "." not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s


def emit_f64_2d(name: str, arr: np.ndarray) -> str:
    rows = ",\n    ".join(
        "[" + ", ".join(fmt_f64(v) for v in row) + "]" for row in arr
    )
    return (
        f"pub static {name}: [[f64; {arr.shape[1]}]; {arr.shape[0]}] = [\n    {rows},\n];\n"
    )


def emit_f64_1d(name: str, arr: np.ndarray) -> str:
    vals = ", ".join(fmt_f64(v) for v in arr)
    return f"pub static {name}: [f64; {len(arr)}] = [{vals}];\n"


def emit_i8_2d(name: str, arr: np.ndarray) -> str:
    assert np.all(arr == np.round(arr)) and np.abs(arr).max() < 127
    rows = ",\n    ".join(
        "[" + ", ".join(str(int(v)) for v in row) + "]" for row in arr
    )
    return (
        f"pub static {name}: [[i8; {arr.shape[1]}]; {arr.shape[0]}] = [\n    {rows},\n];\n"
    )


def main() -> None:
    import skyfield
    import skyfield.nutationlib as nl
    from skyfield.api import load
    from skyfield.data.spice import inertial_frames  # noqa: F401  (import check)
    from skyfield import framelib

    parts = [
        "// AUTO-GENERATED by tools/gen_astro_tables.py from skyfield "
        f"{skyfield.__version__} -- do not edit.\n"
        "// Tables are copied verbatim so Rust output is bit-comparable to\n"
        "// the golden vectors recorded from the same skyfield version.\n"
        "#![allow(clippy::all)]\n\n"
    ]

    # --- IAU 2000A nutation series --------------------------------------
    parts.append(emit_i8_2d("NALS_T", nl.nals_t))  # (678, 5) luni-solar args
    parts.append(emit_f64_2d("LUNISOLAR_LONGITUDE", nl.lunisolar_longitude_coefficients))
    parts.append(emit_f64_2d("LUNISOLAR_OBLIQUITY", nl.lunisolar_obliquity_coefficients))
    parts.append(emit_i8_2d("NAPL_T", nl.napl_t))  # (687, 14) planetary args
    parts.append(emit_f64_2d("PLANETARY_LONGITUDE", nl.nutation_coefficients_longitude))
    parts.append(emit_f64_2d("PLANETARY_OBLIQUITY", nl.nutation_coefficients_obliquity))

    # Fundamental-argument polynomials (Simon et al. 1994), arcseconds.
    fa = np.stack([nl.fa0, nl.fa1, nl.fa2, nl.fa3, nl.fa4])
    parts.append(emit_f64_2d("FA_POLY", fa))  # FA_POLY[k][i]: t^k coeff of arg i

    # Planetary anomaly constants/coefficients (radians).
    parts.append(emit_f64_1d("ANOMALY_CONSTANT", nl.anomaly_constant))
    parts.append(emit_f64_1d("ANOMALY_COEFFICIENT", nl.anomaly_coefficient))

    # Equation-of-equinoxes complementary terms.
    parts.append(emit_i8_2d("KE0_T", nl.ke0_t))
    parts.append(emit_i8_2d("KE1", nl.ke1.reshape(1, -1)))
    parts.append(emit_f64_1d("SE0_T_0", nl.se0_t_0))
    parts.append(emit_f64_1d("SE0_T_1", nl.se0_t_1))
    parts.append(f"pub const SE1_0: f64 = {fmt_f64(nl.se1_0)};\n")
    parts.append(f"pub const SE1_1: f64 = {fmt_f64(nl.se1_1)};\n")

    # --- ICRS frame bias matrix (B in skyfield's M = N.P.B) --------------
    b = framelib.ICRS_to_J2000
    parts.append(emit_f64_2d("FRAME_BIAS_ICRS_TO_J2000", np.asarray(b)))

    # --- delta-T sampled from skyfield's model, monthly 2015-2045 --------
    ts = load.timescale()
    t0 = ts.utc(2015, 1, 1)
    tt_jd = t0.tt + np.arange(0, 30 * 365.25, 30.4375)  # ~monthly
    t = ts.tt_jd(tt_jd)
    parts.append(f"pub const DELTA_T_TT0_JD: f64 = {fmt_f64(tt_jd[0])};\n")
    parts.append(f"pub const DELTA_T_STEP_DAYS: f64 = {fmt_f64(30.4375)};\n")
    parts.append(emit_f64_1d("DELTA_T_TABLE", t.delta_t))

    with open(OUT, "w", newline="\n") as f:
        f.write("".join(parts))
    size = os.path.getsize(OUT)
    print(f"wrote {OUT} ({size/1e3:.0f} kB)")
    print(
        f"nals={nl.nals_t.shape} napl={nl.napl_t.shape} "
        f"delta_t points={len(tt_jd)} "
        f"range {float(t.delta_t[0]):.3f}..{float(t.delta_t[-1]):.3f} s"
    )


if __name__ == "__main__":
    main()
